// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repo_Pattern_Assignment.Models;

#nullable disable

namespace Repo_Pattern_Assignment.Migrations
{
    [DbContext(typeof(HotellDbContext))]
    partial class HotellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repo_Pattern_Assignment.Models.HotelModel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("HotelName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            HotelName = "Siddarth Hotel"
                        },
                        new
                        {
                            HotelId = 2,
                            HotelName = "Prathik Hotel"
                        });
                });

            modelBuilder.Entity("Repo_Pattern_Assignment.Models.RoomModel", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomNo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("RoomPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            HotelId = 0,
                            RoomNo = 111,
                            RoomPrice = 800m,
                            RoomType = "Non Ac"
                        },
                        new
                        {
                            RoomID = 2,
                            HotelId = 0,
                            RoomNo = 112,
                            RoomPrice = 2500m,
                            RoomType = " Ac"
                        });
                });

            modelBuilder.Entity("Repo_Pattern_Assignment.Models.RoomModel", b =>
                {
                    b.HasOne("Repo_Pattern_Assignment.Models.HotelModel", "HotelModel")
                        .WithMany("Room")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelModel");
                });

            modelBuilder.Entity("Repo_Pattern_Assignment.Models.HotelModel", b =>
                {
                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
